FROM ubuntu:latest as builder

RUN apt update && apt install git curl llvm clang cmake make libelf-dev golang-go -y

RUN git clone https://github.com/falcosecurity/libs.git /etc/falco-libs
WORKDIR /etc/falco-libs
RUN git checkout 5a02ca746cda9866d574061fc61c146dae906526
COPY ./kernel/entrypoint.sh /etc/entrypoint.sh

ENTRYPOINT ["/etc/entrypoint.sh"]